---
name:
  en: You Have to Win the Game
desc:
  en: "The Caverns of Legacy as they've come to be known, full of mysterious ruins but plenty of gold and goodies. Will you Lose or Win the Game? [A Sickly Silver Moon]"
ruleSet: Standard
theme: DragonQuest
initialCash: 1100
targetAmount: 50000
baseSalary: 400
salaryIncrement: 200
maxDiceRoll: 6
frbFiles:
  - YHtWtG
background: YHtWtG
mapIcon: YHtWtG
music:
  download:
    - https://drive.google.com/uc?export=download&id=1Iq529T4xNjqOugl3tJkFh4V8rdGFvNoa
  map: YHtWtG_Kicks.50
  targetMet: YHtWtG_Moves.50
  bankruptcy: YHtWtG_Lose.50
  win: YHtWtG_Win.50 #its non looping on purpose don't worry
tourMode:
  bankruptcyLimit: 1
  opponent1: Mario
  opponent2: Waluigi
  opponent3: BowserJr
  clearRank: 1
ventureCards:
  - 1  #   1 Adventurous turning point! You can choose which way to move on your next go, (player's name).
  - 1  #   2 Venture on! Roll the die again and move forward.
  - 1  #   3 Venture through space! Zoom over to any non-venture, non-suit square you like!
  - 0  #   4 Moneymaking venture! Roll the die and get 40 times the number shown in gold coins from the player in 1st place!
  - 1  #   5 Venture through space! Zoom over to any shop or vacant plot!
  - 1  #   6 Venture through space! Zoom over to any venture or suit square!
  - 1  #   7 Special bonus! Your shops all grow by 7%!
  - 1  #   8 Venture on! Everyone's shop prices increase by 30%! Now roll the die and move again.
  - 1  #   9 Venture on! Everyone's shops close for the day! Now roll the die and move again.
  - 0  #  10 Venture on! Everyone's shop prices cut in half! Now roll the die and move again.
  - 1  #  11 Moneymaking venture! Roll the die and get 11 times the number shown in gold coins from all other players!
  - 1  #  12 Capital venture! You can invest capital in any of your shops.
  - 0  #  13 Misadventure! The values of all your shops drop by 13%!
  - 0  #  14 Misadventure! You give everyone 30G each!
  - 1  #  15 Moneymaking venture! Roll the die and get 50 times the number shown in gold coins from the bank!
  - 1  #  16 Random venture! Shops expand in three districts picked at random!
  - 0  #  17 Special bonus! You receive half of your salary!
  - 1  #  18 Misadventure! The bank is forcibly buying you out! You're compelled to sell a shop for only twice its value.
  - 1  #  19 Price hike venture! Your shop prices go up by 30% until your next turn.
  - 1  #  20 Revaluation venture! You can expand any one of your shops by 20%.
  - 1  #  21 Random venture! You receive 20 stocks in a district picked at random!
  - 0  #  22 Cashback venture! You can sell a shop back to the bank for twice its shop value.
  - 1  #  23 Revaluation venture! You can expand any one of your shops by 50%.
  - 1  #  24 Misadventure! The bank is forcibly buying you out! You're compelled to sell a shop for 200G more than its value.
  - 1  #  25 Misadventure! Your shop prices halve until your next turn!
  - 0  #  26 Lucky venture! You get a big commission until your next turn!
  - 1  #  27 Special bonus! You receive 27 times the number of shops you own in gold coins from the bank!
  - 1  #  28 Cameo adventure! A goodybag appears!
  - 1  #  29 Freebie! Take a Heart!
  - 1  #  30 Venture on! All shops charge a 100G flat rate! Now roll the die and move again.
  - 0  #  31 Random venture! Shops expand by 10% in a district picked at random!
  - 1  #  32 Random venture! Shops expand by 20% in a district picked at random!
  - 1  #  33 Cashback venture! You can sell a shop back to the bank for three times its shop value.
  - 1  #  34 Dicey adventure! Roll 1/3/5 and your shops close for the day. Roll 2/4/6 and everyone else's shops close.
  - 0  #  35 Stock venture! You can sell stocks you own at 35% above the market value.
  - 1  #  36 Capital venture! You can pay 100G for the chance to invest in your shops.
  - 1  #  37 Random venture! Shops expand by 30% in a district picked at random!
  - 1  #  38 Stock venture! You can buy stocks in a district of your choice at 10% above the market value.
  - 1  #  39 Suit venture! Buy a Suit Yourself card for 100G.
  - 1  #  40 Misadventure! You give away 10% of your ready cash to the player in last place!
  - 1  #  41 Misadventure! Stock prices fall by 10% in a district picked at random!
  - 1  #  42 Misadventure! Stock prices fall by 20% in a district picked at random!
  - 1  #  43 Misadventure! You pay an assets tax of two gold coins per unit of stock that you own!
  - 0  #  44 Misadventure! Roll the die and pay 44 times the number in gold coins to the player in last place!
  - 1  #  45 Dicey adventure! Roll 1/3/5 to warp to a take-a-break square. Roll 2/4/6 to warp to the arcade.
  - 0  #  46 Misadventure! You drop your wallet and lose 10% of your ready cash!
  - 0  #  47 Dicey adventure! Roll 2-6 to get all the suits. Roll 1 and lose all your suits.
  - 1  #  48 Misadventure! All shops in a district picked at random fall in value by 10%!
  - 0  #  49 Misadventure! All shops in a district picked at random fall in value by 20%!
  - 1  #  50 Venture on! Move forward the same number of squares again.
  - 0  #  51 Venture on! Move forward 1 square more.
  - 0  #  52 Venture on! Move forward another 2 squares.
  - 0  #  53 Venture through space! Zoom over to the bank!
  - 1  #  54 Venture through space! Pay 100G to zoom straight to the bank!
  - 1  #  55 Venture on! Roll the die again and move forward (with an invitation to browse thrown in!).
  - 1  #  56 Venture on! Roll the die again and move forward (with a half-price special offer thrown in!).
  - 1  #  57 Venture through space! Zoom to any square you like.
  - 0  #  58 Venture through space! Pay 100G to zoom to any non-venture, non-suit square you like!
  - 1  #  59 Stock venture! You can buy stocks in a district of your choice at 10% below the market value.
  - 0  #  60 Random venture! Stock prices increase by 10% in a district picked at random!
  - 1  #  61 Special bonus! You receive a 10% dividend on your stocks!
  - 0  #  62 Special bonus! You receive a 20% dividend on your stocks!
  - 1  #  63 Random venture! Stock prices increase by 20% in a district picked at random!
  - 0  #  64 Random venture! Stock prices increase by 30% in a district picked at random!
  - 0  #  65 Forced buyout! You can buy a vacant plot or shop for five times its value, whether someone else owns it or not.
  - 0  #  66 Special bonus! You receive 10 of the most valuable stocks!
  - 1  #  67 Stock venture! You can buy stocks in a district of your choice.
  - 1  #  68 Special arcade adventure! You're invited to play Memory Block!
  - 1  #  69 Stock venture! You can sell stocks you own at 20% above the market value.
  - 1  #  70 Special bonus! You get a sudden promotion and receive a salary! (You lose any suits you have.)
  - 1  #  71 Capital venture! You can invest up to 200G of the bank's money in your shops.
  - 0  #  72 Dicey adventure! Roll 1/3/5 to take 20 times the number of your shops in gold coins. Roll 2/4/6 to pay the same.
  - 1  #  73 Property venture! You can buy any unowned shop or vacant plot.
  - 1  #  74 Misadventure! You are forced to auction one of your shops (with a starting price of twice the shop's value).
  - 1  #  75 Property venture! You can buy any unowned shop or vacant plot for twice its value.
  - 0  #  76 Special arcade adventure! You're invited to play Round the Blocks!
  - 1  #  77 Freebie! Take five of each district's stocks.
  - 1  #  78 Property venture! You can buy any unowned shop or vacant plot for 200G more than its value.
  - 1  #  79 Forced buyout! You can buy a vacant plot or shop for three times its value, whether someone else owns it or not.
  - 1  #  80 Freebie! Take a Spade!
  - 1  #  81 Misadventure! All other players can only move forward 1 on their next turn.
  - 1  #  82 Freebie! Take a Club!
  - 0  #  83 Dicey adventure! Roll 1/3/5 and warp to a random location. Roll 2/4/6 and everyone else warps.
  - 1  #  84 Moneymaking venture! The winning player must pay you 10% of their ready cash!
  - 0  #  85 Moneymaking venture! Roll the die and get 85 times the number shown in gold coins from the bank!
  - 1  #  86 Moneymaking venture! Take 100G from all other players!
  - 0  #  87 Venture on! Roll the special all-7s-and-8s die and move forward again.
  - 0  #  88 Misadventure! All other players swap places!
  - 0  #  89 Freebie! All players take a Suit Yourself card!
  - 0  #  90 Price hike venture! All shop prices go up by 30% until your next turn.
  - 0  #  91 Cameo adventure! A healslime appears!
  - 0  #  92 Cameo adventure! Lakitu appears!
  - 0  #  93 Dicey adventure! Roll 1/3/5 and your shops expand by 10%. Roll 2/4/6 and everyone else's shops expand by 5%.
  - 1  #  94 Freebie! Take a Diamond!
  - 0  #  95 Misadventure! You throw an impromptu party. All other players come to your location!
  - 0  #  96 Misadventure! All players scramble to another player's location!
  - 0  #  97 Stock rise venture! Increase stock value by 20% in a district of your choice.
  - 1  #  98 Forced buyout! You can buy a vacant plot or shop for four times its value, whether someone else owns it or not.
  - 0  #  99 Freebie! What's inside...?
  - 1  # 100 Freebie! Take a Suit Yourself card!
  - 1  # 101 Special bonus! Your shops all grow by 21%!
  - 0  # 102 Moneymaking venture! Roll the die and get 33 times the number shown in gold coins from all other players!
  - 0  # 103 Misadventure! The values of all your shops drop by 25%!
  - 0  # 104 Misadventure! You give everyone 80G each!
  - 0  # 105 Moneymaking venture! Roll the die and get the number shown x your level x 40G from the bank!
  - 0  # 106 Freebie! Roll the die and get half the number shown of Suit Yourself cards! (Decimals will be rounded down.)
  - 0  # 107 Revaluation venture! You can expand any one of your shops by 30%.
  - 0  # 108 Cashback venture! You can sell a shop back to the bank for four times its shop value.
  - 0  # 109 Revaluation venture! You can expand any one of your shops by 75%.
  - 0  # 110 Special bonus! You receive 77 times the number of shops you own in gold coins from the bank!
  - 0  # 111 Cashback venture! You can sell a shop back to the bank for 500G more than its shop value.
  - 0  # 112 Special bonus! You receive 100 times the number of shops you own in gold coins!
  - 0  # 113 Moneymaking venture! Roll the die and get the number shown x your level x 20G from the bank!
  - 0  # 114 Moneymaking venture! Take your level times 40G from all other players!
  - 0  # 115 Misadventure! All other players can only move forward 7 on their next turn.
  - 0  # 116 Moneymaking venture! Roll the die and get 60 times the number shown in gold coins from the player in 1st place!
  - 0  # 117 Adventurous turning point! Everyone gets to choose which way to move on their next go.
  - 0  # 118 Lucky venture! You get a really big commission until your next turn!
  - 0  # 119 Misadventure! You give 20% of your ready cash to the player in last place!
  - 0  # 120 Misadventure! You drop your wallet and lose 20% of your ready cash!
  - 0  # 121 Capital venture! You can invest up to 400G of the bank's money in your shops.
  - 0  # 122 Moneymaking venture! The winning player must pay you 20% of their ready cash!
  - 0  # 123 Dicey adventure! Roll 1/3/5 and your shops expand by 20%. Roll 2/4/6 and everyone else's shops expand by 5%.
  - 0  # 124 Suit venture! Buy a Suit Yourself card for 50G.
  - 0  # 125 Dicey adventure! Roll 1/3/5 to warp to a boon square. Roll 2/4/6 to warp to the arcade.
  - 0  # 126 Revaluation venture! Roll the die and expand your shops by 2% for each number.
  - 0  # 127 Special arcade adventure! You're invited to play Round the Blocks and Memory Block!
  - 0  # 128 Special bonus! You receive 55 times the number of shops you own in gold coins from the bank!
districtNames:
  en:
    - Crimson Roads
    - Cerulean Streets
    - Pitstop Pathway
    - The Underground Underpass
    - Winners Way
    - Prawn Passage
    - Castle Crossroad
    - District H
    - District I
    - District J
    - District K
    - District L
    - District M
    - District N
    - District O
    - District P
shopNames:
  en:
    1: <未設定>10G
    2: <未設定>20G
    3: <未設定>30G
    4: <未設定>40G
    5: Scrap-paper shop
    6: Wool shop
    7: Bottle store
    8: Secondhand book shop
    9: Scrap-metal supplier
    10: Stationery shop
    11: General store
    12: Florist's
    13: Ice-cream shop
    14: Comic-book shop
    15: Dairy
    16: Doughnut shop
    17: Pizza shack
    18: Bakery
    19: Grocery store
    20: Pharmacy
    21: Fish market
    22: Toy shop
    23: Bookshop
    24: Cosmetics boutique
    25: T-shirt shop
    26: Fruit stall
    27: Photography studio
    28: Coffee shop
    29: Butcher shop
    30: Restaurant
    31: Barbershop
    32: Hat boutique
    33: Hardware store
    34: Gift shop
    35: Launderette
    36: Shoe shop
    37: Clothing store
    38: Optician's
    39: Clockmaker's
    40: Furniture shop
    41: Sports shop
    42: Locksmith's
    43: Glassmaker's
    44: Sushi restaurant
    45: Art gallery
    46: Leatherware boutique
    47: Pet shop
    48: Nail salon
    49: Spice shop
    50: Music shop
    51: Surf shop
    52: Boating shop
    53: Cartographer's
    54: Alloy rims shop
    55: Fashion boutique
    56: Waxworks
    57: Lens shop
    58: Kaleidoscope shop
    59: Crystal ball shop
    60: <未設定>600G
    61: Gemstone supplier
    62: Taxidermy studio
    63: <未設定>630G
    64: <未設定>640G
    65: Antiques dealer's
    66: <未設定>660G
    67: <未設定>670G
    68: Goldsmith's
    69: <未設定>690G
    70: Fossil shop
    71: <未設定>710G
    72: Music-box shop
    73: <未設定>730G
    74: <未設定>740G
    75: Marionette workshop
    76: Health shop
    77: <未設定>770G
    78: <未設定>780G
    79: <未設定>790G
    80: Organic food shop
    81: Bridal boutique
    82: <未設定>820G
    83: <未設定>830G
    84: <未設定>840G
    85: Autograph shop
    86: <未設定>860G
    87: <未設定>870G
    88: <未設定>880G
    89: <未設定>890G
    90: Meteorite shop
    91: <未設定>910G
    92: <未設定>920G
    93: <未設定>930G
    94: <未設定>940G
    95: <未設定>950G
    96: <未設定>960G
    97: <未設定>970G
    98: Department store
    99: SYSTEM_MSG_NAME_shop_name_990A
    100: SYSTEM_MSG_NAME_shop_name_1000A
